GET http://localhost:5000/api

###
POST http://localhost:5000/api/signup
Content-Type: application/json

{
        "fullName":"Agnes Lily",
        "email":"agneslily2772@gmail.com",
        "password":"Agnes@2002"
}

###
POST http://localhost:5000/api/signin
Content-Type: application/json

{
        "email":"agneslily2772@gmail.com",
        "password":"Agnes@2002"
}